# Changes here will be overwritten by Copier
_commit: 4.2.0
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: douglas.winter@diamond.ac.uk
author_name: Douglas Winter
component_lifecycle: production
component_owner: group:default/sscc
component_type: service
description: Bluesky plans to be run on Diamond's test rigs e.g. ViSR, P45, etc
distribution_name: test-rig-bluesky
docker: true
docker_debug: true
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: test_rig_bluesky
pypi: false
repo_name: test-rig-bluesky
strict_typing: false
type_checker: pyright
